"""
core/moodlets.py — Stackable named moodlet system.

Moodlets are named, temporary emotional overlays that sit on top of the raw
GoEmotions state. They are more legible (UI-friendly labels like "Well Rested",
"Flirty", "Inspired") and stack additively.

The dominant moodlet drives the displayed emotion label in get_state().
Moodlets are generated by interactions, needs events, weather, and illness.

MoodletStack is attached to each Sim as sim.moodlets.
"""
from __future__ import annotations

import random
from dataclasses import dataclass, field
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from core.sim import Sim

MAX_MOODLETS = 8   # cap on concurrent moodlets per sim


@dataclass
class Moodlet:
    label: str          # display name: "Well Rested", "Inspired", etc.
    emotion: str        # underlying GoEmotions label
    intensity: float    # 0.0..1.0
    duration: int       # ticks remaining
    valence: float      # +/- overall mood contribution
    source: str = ""    # what generated this moodlet

    def tick(self) -> bool:
        """Decay one tick. Returns True if expired."""
        self.duration -= 1
        return self.duration <= 0


# ── Pre-defined moodlet library ───────────────────────────────────────────────

MOODLET_DEFS: dict[str, dict] = {
    # Positive
    "well_rested":         {"emotion": "relief",      "intensity": 0.6, "valence": +0.5, "duration": 6},
    "inspired":            {"emotion": "optimism",    "intensity": 0.7, "valence": +0.6, "duration": 8},
    "flirty":              {"emotion": "desire",      "intensity": 0.6, "valence": +0.4, "duration": 5},
    "on_a_roll":           {"emotion": "excitement",  "intensity": 0.7, "valence": +0.5, "duration": 6},
    "just_had_fun":        {"emotion": "joy",         "intensity": 0.5, "valence": +0.4, "duration": 4},
    "deeply_connected":    {"emotion": "love",        "intensity": 0.8, "valence": +0.7, "duration": 8},
    "proud":               {"emotion": "pride",       "intensity": 0.6, "valence": +0.5, "duration": 5},
    "grateful":            {"emotion": "gratitude",   "intensity": 0.6, "valence": +0.5, "duration": 4},
    "energised":           {"emotion": "excitement",  "intensity": 0.5, "valence": +0.4, "duration": 5},
    "sunshine_mood":       {"emotion": "optimism",    "intensity": 0.4, "valence": +0.3, "duration": 4},
    "full_and_happy":      {"emotion": "joy",         "intensity": 0.4, "valence": +0.3, "duration": 3},
    "gig_rush":            {"emotion": "excitement",  "intensity": 0.7, "valence": +0.5, "duration": 6},
    "newly_wed":           {"emotion": "love",        "intensity": 1.0, "valence": +0.9, "duration": 20},
    # Negative
    "uncomfortable":       {"emotion": "discomfort",  "intensity": 0.5, "valence": -0.4, "duration": 4},
    "stressed":            {"emotion": "nervousness", "intensity": 0.6, "valence": -0.5, "duration": 6},
    "embarrassed":         {"emotion": "embarrassment","intensity":0.6, "valence": -0.4, "duration": 4},
    "heartbroken":         {"emotion": "grief",       "intensity": 0.9, "valence": -0.8, "duration": 15},
    "fighting_illness":    {"emotion": "discomfort",  "intensity": 0.7, "valence": -0.6, "duration": 8},
    "too_cold":            {"emotion": "discomfort",  "intensity": 0.5, "valence": -0.4, "duration": 3},
    "rainy_day_blues":     {"emotion": "sadness",     "intensity": 0.3, "valence": -0.2, "duration": 3},
    "betrayed":            {"emotion": "grief",       "intensity": 0.8, "valence": -0.7, "duration": 10},
    "drama_witnessed":     {"emotion": "surprise",    "intensity": 0.4, "valence": -0.2, "duration": 3},
    "broke":               {"emotion": "nervousness", "intensity": 0.6, "valence": -0.5, "duration": 5},
}


class MoodletStack:
    """Stackable moodlet container attached to each Sim."""

    def __init__(self) -> None:
        self._moodlets: list[Moodlet] = []

    def add(self, key: str, source: str = "", override_duration: int | None = None) -> None:
        defn = MOODLET_DEFS.get(key)
        if defn is None:
            return
        # Replace existing moodlet of same key rather than stacking duplicates
        self._moodlets = [m for m in self._moodlets if m.label != key]
        duration = override_duration if override_duration is not None else defn["duration"]
        self._moodlets.append(Moodlet(
            label     = key,
            emotion   = defn["emotion"],
            intensity = defn["intensity"],
            duration  = duration,
            valence   = defn["valence"],
            source    = source,
        ))
        # Trim to cap
        if len(self._moodlets) > MAX_MOODLETS:
            # Remove weakest-intensity moodlet
            self._moodlets.sort(key=lambda m: m.intensity)
            self._moodlets = self._moodlets[1:]

    def tick(self) -> None:
        self._moodlets = [m for m in self._moodlets if not m.tick()]

    def dominant(self) -> Moodlet | None:
        if not self._moodlets:
            return None
        return max(self._moodlets, key=lambda m: m.intensity)

    def dominant_label(self) -> str | None:
        d = self.dominant()
        return d.label if d else None

    def dominant_emotion(self) -> str | None:
        d = self.dominant()
        return d.emotion if d else None

    def net_valence(self) -> float:
        if not self._moodlets:
            return 0.0
        return round(sum(m.valence for m in self._moodlets) / len(self._moodlets), 3)

    def active(self) -> list[dict]:
        return [
            {"label": m.label, "emotion": m.emotion, "intensity": m.intensity,
             "duration": m.duration, "valence": m.valence}
            for m in self._moodlets
        ]

    def has(self, key: str) -> bool:
        return any(m.label == key for m in self._moodlets)
